### ISSUE TITLE
Working on github actions

### ISSUE THREAD

**Issue by lrnv** [rbarazzutti/gitinfo2-latexmk#3]
I have troubles making this work on github actions ? I have a github action that looks like : 

```
---
name: "Release pdf"

on:
  push:
    branches:
      - "master"

jobs:
  release_cv:
    name: "Release CV"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v1
    - name: Compile CV
      uses: xu-cheng/latex-action@master
      with:
        root_file: CV.tex
    - name: Check pdf file
      run: |
        file CV.pdf | grep -q ' PDF '
    - name: "Upload"
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Build"
        files: |
          CV.pdf
```

which is supposed to release my CV online. It works great, and since it runs on github actions Hooks are not possible. 

Adding `do './tex/gitinfo2.pm';` to my `.latexmkrc` only yields : 
```
sh: git: not found
sh: git: not found
sh: git: not found
```
while running `gitinfo2.pm`. I suppose this is because standard git commands do not work in a github action context. Do you think there is still something we can do ?
